language: ruby
before_script: ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
script: ruby -Ilib -Itest -rrubygems test/test_all.rb
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-nightly-18mode
  - rbx-nightly-19mode
  - jruby-18mode
  - jruby-19mode
